### ISSUE TITLE
System.NullReferenceException in NavigationView.cs -> SelectSingleItemCore

### ISSUE THREAD

**Issue by hematec** [PieroCastillo/Aura.UI#10]
When selecting a NavigationViewItem and previously, nothing was selected, a System.NullReferenceException occours here:
`(SelectedItem as ISelectable).IsSelected = false;`
maybe it could be changed to:
`if (SelectedItem != null) (SelectedItem as ISelectable).IsSelected = false;`

BR

**Comment by PieroCastillo** [comment]
> When selecting a NavigationViewItem and previously, nothing was selected, a System.NullReferenceException occours here:
> `(SelectedItem as ISelectable).IsSelected = false;`
> maybe it could be changed to:
> `if (SelectedItem != null) (SelectedItem as ISelectable).IsSelected = false;`
> 
> BR

you should select an element by xaml, like this:https://github.com/PieroCastillo/Aura.UI/blob/aec247e8548029836c82445244aaaed84433e91d/samples/Aura.UI.Gallery/Views/MainView.axaml#L19-L22

**Comment by PieroCastillo** [comment]
it's fixed, https://github.com/PieroCastillo/Aura.UI/blob/f1fbe7c784e5e2dca1f16bbcd6741c4e65925f82/src/Aura.UI/Controls/Navigation/NavigationView/NavigationView.cs#L77-L78
https://github.com/PieroCastillo/Aura.UI/blob/f1fbe7c784e5e2dca1f16bbcd6741c4e65925f82/src/Aura.UI/Controls/Navigation/NavigationView/NavigationView.cs#L196-L202
