### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PieroCastillo** [PieroCastillo/Aura.UI#11]
## 0.1.4
- NavigationView MVVM support [WIP]
- AuraTabView MVVM support _[Done]_
- CardCollection MVVM support _[Done]_
- FlutterButtonBar MVVM support [WIP]
- CardControl Command & CommandParameter properties _[Done]_
- Refresh NavigationView Style [WIP]
- Remake SearchSystem in NavigationView.
- Fixed Title for NavigationView _[Done]_

## 0.1.5
- NavigationView History
- Mobile controls (maybe with Flutter styles)
- ColorPicker [WIP]
- AudioPlayer 
- Attached Properties for common uses, like these:
```
<TextBlock AuraProperties.TextBlockTextType="H1"/>
<TextBlock AuraProperties.TextBlockTextType="H2"/>
<TextBlock AuraProperties.TextBlockTextType="H3"/> //maybe until H6
```

**Comment by hailstorm75** [comment]
Hello! What is the state of the `NavigationView` MVVM support? The required item template tags are present; however, when using them the control style gets broken. If you are not aware of this problem I can create an issue with all of the specifics, possibly help fix it.

**Comment by PieroCastillo** [comment]
> Hello! What is the state of the `NavigationView` MVVM support? The required item template tags are present; however, when using them the control style gets broken. If you are not aware of this problem I can create an issue with all of the specifics, possibly help fix it.

It's a bit complex, but I think the implementation is similar to ThreeView (remember NavigationView class inherits from ThreeView), I was working in a TriangleColorPicker, when it will be done I gonna work in the nv mvvm support👌

**Comment by PieroCastillo** [comment]
moved to projects
