### ISSUE TITLE
NavigationView Background Color

### ISSUE THREAD

**Issue by eliudfromkenya** [PieroCastillo/Aura.UI#17]
How can one change navigation background color to custom color?

**Comment by PieroCastillo** [comment]
with the property "Background"
![image](https://user-images.githubusercontent.com/39932324/127792319-f1a3da50-b359-4d23-8532-fd4c62a25352.png)

**Comment by PieroCastillo** [comment]
or if you want to replace the Panel Acrylic Material you can override the ```NavigationViewMaterial``` resource (for the next previous release I'm going to put a PanelMaterial property)

**Comment by eliudfromkenya** [comment]
Am really grateful for your dedicated support.
Thanks Thanks Thanks.
I was asking for that part that contains icons or navigation title.
![127792319-f1a3da50-b359-4d23-8532-fd4c62a25352](https://user-images.githubusercontent.com/16660350/129465809-c4241e94-9c57-44bd-b189-9372840a1060.png)

**Comment by PieroCastillo** [comment]
sorry for not seeing your comment on this issue, to edit the panel's background you need to change the property ```PanelMaterial``` like this:
![image](https://user-images.githubusercontent.com/39932324/140254890-89b3046a-a557-410c-87c6-65af71ec4dad.png)

**Comment by eliudfromkenya** [comment]
Thanks
