### ISSUE TITLE
0.1.3-preview3 installation problem

### ISSUE THREAD

**Issue by mehmetulukaya** [PieroCastillo/Aura.UI#2]
I am trying to install last preview of Aura.UI but it is giving imcompitable error but 0.1.2 is not giving any error.

Önem Derecesi	Kod	Açıklama	Proje	Dosya	Çizgi	Gizleme Durumu
Hata	NU1202	ColorPicker 1.0.0 paketi, netcoreapp3.1 (.NETCoreApp,Version=v3.1) ile uyumlu değil. ColorPicker 1.0.0 paketi şunları destekler: portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32)	Avalonia-Ex03	D:\Git\C_Sharp_Projects\Avalonia-Ex03\Avalonia-Ex03\Avalonia-Ex03.csproj	1	

My avalonia is:
Avalonia 0.10.0-preview5

and related other packages

**Comment by PieroCastillo** [comment]
> Hata NU1202 ColorPicker 1.0.0 paketi, netcoreapp3.1 (.NETCoreApp,Version=v3.1) ile uyumlu değil. ColorPicker 1.0.0 paketi şunları destekler: portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32) Avalonia-Ex03 D:\Git\C_Sharp_Projects\Avalonia-Ex03\Avalonia-Ex03\Avalonia-Ex03.csproj 1
> 
> My avalonia is:

yes, i'm working to fix it, in some hours i'll  release a package fixed

**Comment by PieroCastillo** [comment]
> I am trying to install last preview of Aura.UI but it is giving imcompitable error but 0.1.2 is not giving any error.
> 
> Önem Derecesi Kod Açıklama Proje Dosya Çizgi Gizleme Durumu
> Hata NU1202 ColorPicker 1.0.0 paketi, netcoreapp3.1 (.NETCoreApp,Version=v3.1) ile uyumlu değil. ColorPicker 1.0.0 paketi şunları destekler: portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32) Avalonia-Ex03 D:\Git\C_Sharp_Projects\Avalonia-Ex03\Avalonia-Ex03\Avalonia-Ex03.csproj 1
> 
> My avalonia is:
> Avalonia 0.10.0-preview5
> 
> and related other packages

ok, it's fixed, download from this link https://www.nuget.org/packages/Aura.UI/0.1.3-preview5

**Comment by PieroCastillo** [comment]
> I am trying to install last preview of Aura.UI but it is giving imcompitable error but 0.1.2 is not giving any error.
> 
> Önem Derecesi Kod Açıklama Proje Dosya Çizgi Gizleme Durumu
> Hata NU1202 ColorPicker 1.0.0 paketi, netcoreapp3.1 (.NETCoreApp,Version=v3.1) ile uyumlu değil. ColorPicker 1.0.0 paketi şunları destekler: portable-win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile32) Avalonia-Ex03 D:\Git\C_Sharp_Projects\Avalonia-Ex03\Avalonia-Ex03\Avalonia-Ex03.csproj 1
> 
> My avalonia is:
> Avalonia 0.10.0-preview5
> 
> and related other packages

now try with Aura.UI.0.1.3-preview6

**Comment by mehmetulukaya** [comment]
It is OK compiled!
