### ISSUE TITLE
FloatingButtonBar Ideas

### ISSUE THREAD

**Issue by timunie** [PieroCastillo/Aura.UI#21]
Hi @PieroCastillo 

while playing with the `FloatingButtonBar` I got some ideas:
1. The `Icon` is of type `IImage` instead I would like it to be of type `object` and add a `StyledProperty` of type `IDataTemplate` called `IconTemplate`
2. when the view loades I noticed that the floating buttons are shown for a few miliseconds. I would like to change this behavior if I manage to find a way around this. You can also notice this in the designer. 

I'll provide a PR if I manage to get it implemented. 

Happy coding
Tim

**Comment by PieroCastillo** [comment]
it's a good idea!

**Comment by timunie** [comment]
I made a PR for 1) (see #22), but I did not get around issue 2). It may be an issue in Avalonia itself or here. So I'll open a new Ticket here in order to trtack this further.
