### ISSUE TITLE
FloatingButtonBar should not animate when shown for the first time

### ISSUE THREAD

**Issue by timunie** [PieroCastillo/Aura.UI#23]
This is issue is transferred for #21 

when the view loades I noticed that the floating buttons are shown for a few miliseconds. I would like to change this behavior if I manage to find a way around this. You can also notice this in the designer.

Video demonstrating the issue:
![FloatingButtonAnimationIssue](https://user-images.githubusercontent.com/47110241/135614654-3128d9df-920c-4d54-903c-73e5573b21a3.png)

Happy coding
Tim

**Comment by PieroCastillo** [comment]
I see it, now I'm trying to fix it

**Comment by timunie** [comment]
transferred this issue to Avalonia: https://github.com/AvaloniaUI/Avalonia/issues/6676

**Comment by timunie** [comment]
Closing this issue here as it seems to be caused in Avalonia itself.
