### ISSUE TITLE
FloatingBarButton sizing

### ISSUE THREAD

**Issue by timunie** [PieroCastillo/Aura.UI#24]
Hi @PieroCastillo 

I love the round shape of the buttons very well. However when changing the dynamic resource `FloatingButtonSize` to another size the shape will change because the `CornerRadius` is hard-coded. 

I have a solution for this via `IValueConverter`. We can take either the Height or Width of the Control and calculate the needed `CornerRadius`

I'll prepare another PR for this next week I think. 

Have a nice weekend

**Comment by PieroCastillo** [comment]
It's a good idea, but I think it's better use ```Bounds``` instead ````Width & Height``` properties

**Comment by timunie** [comment]
> but I think it's better use Bounds instead Width & Height properties

Absolutely and also the way I wanted it to do. It came just because I just switched from WPF and there is no such property. It would have helped me in WPF so many times 😆
