### ISSUE TITLE
How to bind AuraTabView Items to ObservableCollection

### ISSUE THREAD

**Issue by Shadow4walker** [PieroCastillo/Aura.UI#27]
it used to work in previous releases with some modified in the Data Template  but now in "0.1.4.1" I got some exception System.ArgumentNullException: 'Value cannot be null. (Parameter 'target')'""
the Exception happened in Aura.UI.Controls.Generators.AuraTabItemContainerGenerator.CreateContainer

View
> 
    <AuraTabView TabStripPlacement="Left" Items="{Binding Peoples}">
        <AuraTabView.ItemTemplate>
            <DataTemplate>
                <StackPanel>
                    <TextBlock Text="{Binding Name}" />
                    <TextBlock Text="{Binding Age}" />
                </StackPanel>
            </DataTemplate>
        </AuraTabView.ItemTemplate>
    </AuraTabView>
> 
VM

> 
        private protected ObservableCollection<Person> Peoples { get; } = new();
> 
Person

> 
    public class Person {
        public Person(string name, string age) {
            Name = name;
            Age = age;
        }

        public string Name { get; }
        public string Age { get; }
    }
>

**Comment by PieroCastillo** [comment]
wait... how are you using it? the items what are you using should implement ```IAuraTabItemTemplate```

**Comment by Shadow4walker** [comment]
i've switched to Avalonia TabControl.
already tried with IAuraTabItemTemplate and the items just not displayed! can u give me example project with the worked solution

**Comment by PieroCastillo** [comment]
you're right, I remember with Avalonia 0.10.1 works fine... but now it's broken, I'm gonna work now to fix it

**Comment by PieroCastillo** [comment]
to display items it's ok, I'm gonna add a sample adding/deleting items, and using data Templates
![image](https://user-images.githubusercontent.com/39932324/140254111-b30f2e44-ed3d-43dc-917c-c17dc6872c15.png)

**Comment by PieroCastillo** [comment]
it's done, now should work like the Avalonia sample

**Comment by Shadow4walker** [comment]
> it's done, now should work like the Avalonia sample https://github.com/PieroCastillo/Aura.UI/blob/master/MVVMSamples/AuraTabViewMVVMSample/ViewModels/MainWindowViewModel.cs https://github.com/PieroCastillo/Aura.UI/blob/master/MVVMSamples/AuraTabViewMVVMSample/Views/MainWindow.axaml

all working great thank you.
btw have you considered adding those two suggestions [ScrollAble header Header with Remove item event](https://github.com/PieroCastillo/Aura.UI/issues/7#issuecomment-830494509) it would be easier to just integrate this two suggestion by default within AuraTabView rather than edit template in each use

**Comment by PieroCastillo** [comment]
I think now I can close this issue :), also, could you open another issue specifing other details about the closing bug?

**Comment by Shadow4walker** [comment]
just wanted to tell you this issue still exist after your last update you may check is using your samples! 

> System.ArgumentNullException: 'Value cannot be null. (Parameter 'target')'

**Comment by PieroCastillo** [comment]
Fill the property "IsClosable"
