### ISSUE TITLE
The type initializer for 'Aura.UI.Controls.TitleBar' threw an exception.

### ISSUE THREAD

**Issue by danieladacruz** [PieroCastillo/Aura.UI#4]
Hi
After I import the latest nuget in the project and then add 

<StyleInclude Source="avares://Aura.UI/AuraUI.xaml"/>

into my App.xaml I get the exception "The type initializer for 'Aura.UI.Controls.TitleBar' threw an exception."

any idea why?
thanks

**Comment by PieroCastillo** [comment]
sorry for not replying earlier, that happened in the old version, use [Aura.UI 0.1.3-rc1](https://www.nuget.org/packages/Aura.UI/0.1.3-rc1), the TitleBar control has been renamed to TitleBox.

**Comment by PieroCastillo** [comment]
I still recommend using the GroupBox control, maybe in the future I will remove the TitleBox control.
