### ISSUE TITLE
NavigationView preselect item

### ISSUE THREAD

**Issue by WizMe-M** [PieroCastillo/Aura.UI#40]
Checked out sample Aura.UI.Gallery, that first NavigationViewItem is selected after the app launches. Is there some automatic selection of first item logic?
I tried to reproduce this logic on minimal code base, so

    <NavigationView Header="Aura">
        <NavigationViewItem Header="Item 1" />
        <NavigationViewItem Header="Item 2" />
    </NavigationView>

code above is working in this repo's solution (first item has been selected and NavigationView.SelectedContent equals `Content`), but it isn't in my empty project (no one item selected and SelectedContent is `null`).

Seems like i'm missing something imporant, but cannot find out what. Couldn't you hint me how does it works?

**Comment by PieroCastillo** [comment]
```
<NavigationView Header="Aura" SelectedItem="#Item">
    <NavigationViewItem Header="Item 1" />
    <NavigationViewItem Name="Item" Header="Item 2" />
</NavigationView>
```

I think with this should be enought, also, try to use the last dev version

**Comment by WizMe-M** [comment]
Yeah, this works for me, but still i'm stucked why does it work only this way.
NavigationView control in MainView.xaml doesn't set SelectedItem prop and all right.

Also tried with dev version - same results
