### ISSUE TITLE
Support Old Avalonia DefaultTheme

### ISSUE THREAD

**Issue by Shadow4walker** [PieroCastillo/Aura.UI#5]
thanks for creating these controls looks neat!
is there a way to use these controls with old Avalonia Theme (BaseDark,BaseLight)?

I'm getting some error like this when using Old DefaultTheme
`KeyNotFoundException: Static resource 'SystemBaseHighColor' not found.
`

**Comment by PieroCastillo** [comment]
mmm, yes, I'm going to work in support the default theme, maybe adding two Resources files, like ```Aura.UI.Resources.Default.xaml``` & ```Aura.UI.Resources.Fluent.xaml```

**Comment by PieroCastillo** [comment]
but now Aura.UI supports the FluentTheme only :(

**Comment by PieroCastillo** [comment]
mmmm, u can add ```<StyleInclude Source="avares://Avalonia.Themes.Fluent/Accents/BaseLight.xaml"/>```` to fix the error, the principal problem is there are a lot of colors in the Fluent Theme that are not exist in the default theme.
