### ISSUE TITLE
MessageBox/ContentDialog Not DIsplaying

### ISSUE THREAD

**Issue by nlogozzo** [PieroCastillo/Aura.UI#8]
So I have my main window code-behind and I have a button in XAML. I link my button to a click handler that in theory should open a messagebox when clicked, however nothing happens. I've tried all the folowing code below and no dialog ever shows. I'm using Linux with the GNOME 40 desktop enviornment.

```csharp
private void ButtonClick(object sender, RoutedEventArgs e)
{
    var msg = new MessageDialog();
    msg.SetOwner(this);
    msg.Show(); //Dialog never shows and no error message occurs
}
```

This issue also occurs with:
```csharp
private void ButtonClick(object sender, RoutedEventArgs e)
{
    this.NewMessageDialog("test", "test", null); //Dialog never shows and no error message occurs
}
```

This issue also occurs if i change MessageDialog to ContentDialog. I could be totally not doing this right, but from the sample you provided this is what I came up with :man_shrugging:

**Comment by PieroCastillo** [comment]
> So I have my main window code-behind and I have a button in XAML. I link my button to a click handler that in theory should open a messagebox when clicked, however nothing happens. I've tried all the folowing code below and no dialog ever shows. I'm using Linux with the GNOME 40 desktop enviornment.
> 
> ```cs
> private void ButtonClick(object sender, RoutedEventArgs e)
> {
>     var msg = new MessageDialog();
>     msg.SetOwner(this);
>     msg.Show(); //Dialog never shows and no error message occurs
> }
> ```
> 
> This issue also occurs with:
> 
> ```cs
> private void ButtonClick(object sender, RoutedEventArgs e)
> {
>     this.NewMessageDialog("test", "test", null); //Dialog never shows and no error message occurs
> }
> ```
> 
> This issue also occurs if i change MessageDialog to ContentDialog. I could be totally not doing this right, but from the sample you provided this is what I came up with 🤷‍♂️

mmm, so strange, I'm gonna install an VM to see the error, but, did u import AuraUI.xaml?

**Comment by PieroCastillo** [comment]
ah, what's ur OS exactly?

**Comment by PieroCastillo** [comment]
I think that's can be an Avalonia bug, 'cause the ContentDialog control does not use unmanaged or platform specific code; just uses the OverlayLayer, this is managed by Avalonia...

**Comment by nlogozzo** [comment]
Arch Linux with gnome desktop 
But I'm a total idiot...I totally forgot to include the style in App.xaml 
I'm at work rn so I'll include it later and lyk what happens

**Comment by PieroCastillo** [comment]
xdd

**Comment by PieroCastillo** [comment]
@nlogozzo  it's fixed?

**Comment by nlogozzo** [comment]
Still waiting to try...won’t be home till 10 PM EST today...late night :)

**Comment by nlogozzo** [comment]
Fixed by adding styles
